name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  test:
    name: npm test
    uses: percebus/github-actions-npm/.github/workflows/test.yml@main
    with:
      list-tests: all

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: percebus/github-actions-common/.github/actions/checkout@main
    #   - uses: percebus/github-actions-node/.github/actions/setup@main
    #   - uses: percebus/github-actions-npm/.github/actions/install@main

    #   - name: npm test
    #     run: npm test
    #   - uses: percebus/github-actions-testing/.github/actions/junit@main
    #     with:
    #       list-tests: all


  testem:
    if: false # FIXME not working
    name: "test'em"
    needs: test
    uses: percebus/github-actions-npm/.github/workflows/run_script.yml@main
    with:
      script: testem:ci:dot


  tests:
    if: github.ref == 'refs/heads/main'
    needs: test
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        node:
          - '' # default (20 as of 2025-10-11)
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: npm test @ node:${{ matrix.node }}@${{ matrix.os }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/setup@main
        with:
          node-version: ${{ matrix.node }}

      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: npm test
        run: npm test
      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          tests_name: Unit Tests @ node:${{ matrix.node }}@${{ matrix.os }}
          summary_title: ""
          publish-test-deltas: "false"
