name: "[C]ontinuous [I]ntegration"
on:
  push:

jobs:
  # SRC https://medium.com/attest-product-and-technology/adding-a-unique-github-build-identifier-7aa2e83cadca
  id:
    name: Build Id
    runs-on: ubuntu-latest
    steps:
      - name: id
        id: id
        run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
      - name: echo
        run: echo ${{ env.BUILD_ID }}

  audit:
    needs: id
    uses: percebus/github-actions-npm/.github/workflows/npm_audit.yml@main

  # FIXME merge jest:ci steps
  test:
    name: npm test
    needs: id
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: npm run jest:ci:unit:js
        run: npm run jest:ci:unit:js
      - name: junit.xml
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Unit Tests: JS"
          path: junit.xml
          reporter: jest-junit

      - name: npm run jest:ci:unit:es6
        run: npm run jest:ci:unit:es6
      - name: junit.xml
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Unit Tests: ES6"
          path: junit.xml
          reporter: jest-junit

  testem:
    if: false # FIXME not working
    name: "test'em"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: testem:ci
        run: npm run testem:ci:dot


  tests:
    # if: github.ref == 'refs/heads/main'
    needs: test
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        node:
          - '' # default (LTS)
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
        os:
          - ubuntu-latest
#         - macOS-latest # FIXME
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: npm test @ node:${{ matrix.node }}@${{ matrix.os }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
        with:
          node-version: ${{ matrix.node }}

      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: npm run jest:ci:unit:js
        run: npm run jest:ci:unit:js
      - name: junit.xml
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "Unit Tests: JS @ node:${{ matrix.node }}"
          path: junit.xml
          reporter: jest-junit
