name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  # TODO move me to common
  # SRC https://medium.com/attest-product-and-technology/adding-a-unique-github-build-identifier-7aa2e83cadca
  id:
    name: Build Id
    runs-on: ubuntu-latest
    steps:
      - name: id
        id: id
        run: echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
      - name: echo
        run: echo ${{ env.BUILD_ID }}

  test:
    needs: id
    uses: percebus/github-actions-npm/.github/workflows/npm_test.yml@main
    with:
      reporter: jest-junit
      list-tests: all
      files_pattern: junit.xml

  testem:
    if: false # FIXME not working
    name: "test'em"
    needs: test
    uses: percebus/github-actions-npm/.github/workflows/npm_run_script.yml@main
    with:
      script: testem:ci:dot


  tests:
    if: github.ref == 'refs/heads/main'
    needs: test
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        node:
          - '' # default (LTS)
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
        os:
          - ubuntu-latest
#         - macOS-latest # FIXME
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: npm test @ node:${{ matrix.node }}@${{ matrix.os }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-node/.github/actions/node_setup@main
        with:
          node-version: ${{ matrix.node }}

      - uses: percebus/github-actions-npm/.github/actions/npm_install@main

      - name: npm test
        run: npm test
      - uses: percebus/github-actions-testing/.github/actions/test-reporter@main
        with:
          name: Unit Tests @ node:${{ matrix.node }}@${{ matrix.os }}
          reporter: jest-junit
          files_pattern: junit.xml
          list-suites: all
          list-tests: failed
